name: Docker lab3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

  deliverit:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: build docker image and push to hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
          image: docker pull mahmoud1499/myapp-repo
          registry: docker.io
          dockerfile: Dockerfile
          username: mahmoud1499
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest  
